---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance-centos-8
    image: docker.io/pycontribs/centos:8
    pre_build_image: true
  - name: instance-centos-7
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
  - name: instance-fedora
    image: docker.io/pycontribs/fedora
    pre_build_image: true

provisioner:
  name: ansible
verifier:
  name: ansible
